version: "3"
services:
  nginx:
    build:
      context: ./docker/environments/dev/nginx
      dockerfile: ./Dockerfile
    container_name: veci_nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./symfony:/var/www/project
      - ./docker/environments/dev/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/logs/nginx:/var/log/nginx
    links:
      - php

  php:
    build:
      context: ./docker/environments/dev/php
      args:
        UID: $U_ID
    container_name: veci_php
    working_dir: /var/www/project
    env_file:
      - .symfony.env
    volumes:
      - ./symfony:/var/www/project:rw,cached
      - ./docker/logs/php:/var/log
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0.36
    container_name: veci_db
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=4G --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .mysql.env
    volumes:
      - ./docker/data/mysql:/var/lib/mysql:rw,delegated

  redis:
    image: redis:7.2-alpine
    container_name: veci_redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./docker/data/redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: veci_redis_gui
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"