api_platform:
    title: VECI API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']

    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']

    defaults:
        stateless: true
        pagination_items_per_page: 20
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

    collection:
        pagination:
            enabled_parameter_name: pagination # optional
            items_per_page_parameter_name: itemsPerPage

    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header
    keep_legacy_inflector: false
    use_symfony_listeners: true