liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        avatar:
            quality: 75
            filters:
                thumbnail: { size: [40, 40], mode: outbound }
        thumbnail4x3:
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
    twig:
        mode: lazy
